#!/bin/bash
echo "========================================"
echo "   CYBЕРГRAM - ИНСТРУКЦИЯ ПО СБОРКЕ   "
echo "========================================"
echo ""
echo "Этот Android проект не может быть собран в Replit."
echo "Для сборки APK вам нужно:"
echo ""
echo "1. УСТАНОВИТЕ Android Studio на локальный компьютер"
echo "   Скачайте: https://developer.android.com/studio"
echo ""
echo "2. ПОЛУЧИТЕ TELEGRAM API КЛЮЧИ:"
echo "   - Откройте: https://my.telegram.org"
echo "   - Войдите с номером телефона"
echo "   - API development tools"
echo "   - Запишите APP_ID и APP_HASH"
echo ""
echo "3. ВСТАВЬТЕ КЛЮЧИ В ФАЙЛ:"
echo "   TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java"
echo "   Строка 29: public static int APP_ID = ВАШ_APP_ID;"
echo "   Строка 30: public static String APP_HASH = \"ВАШ_APP_HASH\";"
echo ""
echo "4. СОБЕРИТЕ APK:"
echo "   - Откройте проект в Android Studio"
echo "   - Build -> Build Bundle(s) / APK(s) -> Build APK(s)"
echo "   - APK будет в: TMessagesProj/build/outputs/apk/"
echo ""
echo "========================================"
echo "   ИЗМЕНЕНИЯ В CYBERGRAM:"
echo "========================================"
echo "✓ Название изменено на CyberGram"
echo "✓ Добавлена кнопка 'Cyber Sec' в профиле"
echo "✓ Создан экран с функциями анонимности"
echo "========================================"
