[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "aiogram>=3.22.0",
    "aiosqlite>=0.21.0",
    "cachetools>=6.2.0",
    "g4f>=0.6.3.0",
]
