name: Build CyberGram APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK 21.4.7075529
      run: |
        yes | sdkmanager "ndk;21.4.7075529"
        echo "ndk.dir=$ANDROID_HOME/ndk/21.4.7075529" >> $GITHUB_WORKSPACE/local.properties
        echo "sdk.dir=$ANDROID_HOME" >> $GITHUB_WORKSPACE/local.properties

    - name: Install CMake 3.10.2
      run: |
        yes | sdkmanager "cmake;3.10.2.4988404"

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Standalone APK
      run: ./gradlew :TMessagesProj_AppStandalone:assembleStandalone --stacktrace --info

    - name: Sign APK
      id: sign_app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: TMessagesProj_AppStandalone/build/outputs/apk/standalone/
        signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

    - name: Upload Signed APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cybergram-apk-${{ github.sha }}
        path: TMessagesProj_AppStandalone/build/outputs/apk/standalone/app*.apk
        retention-days: 30

    - name: Send APK to Telegram
      if: success() && github.ref == 'refs/heads/main'
      uses: appleboy/telegram-action@v0.1.1
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ✅ CyberGram APK built successfully!
          Commit: ${{ github.sha }}
          Branch: ${{ github.ref }}
          Download from: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        document: TMessagesProj_AppStandalone/build/outputs/apk/standalone/app-standalone.apk